!function(d,y,n,a,m,i,c,p,l,u,s){{if(typeof window.DMP!=typeof function(){})return;if(!DMP.bStub)return;if(!window.postMessage||!window.addEventListener||!window.JSON)return;try{if(!window.localStorage)return}catch(_){return}var oStubDMP=DMP}var fScramble=function(sString){var aString=(""+sString).split("");for(var i=0;i<aString.length;++i){var iChar=aString[i].charCodeAt(0);if(iChar>=33&&iChar<=126)aString[i]=String.fromCharCode(33+(iChar+14)%94)}return aString.reverse().join("")};{var oIFrame=null;
var bIFrame=false;var aIFrame=[];var fIFrame=function(mMessage){if(!bIFrame){aIFrame.push([].slice.call(arguments));return void 0}try{if(!oIFrame||!oIFrame.contentWindow||!oIFrame.contentWindow.postMessage)return null;if(oDMP._.debug&&window.console&&console.log)console.log("DMP Proxy Sent",mMessage);oIFrame.contentWindow.postMessage(mMessage,"*");return true}catch(_$0){}return false}}{var sDomainTLD=location.hostname.split(".").slice(-2).join(".").toLowerCase()||"";var oDMP={_:{domain:sDomainTLD,
debug:false,read_only:false,extended:false,user_info:"",context:{},count:{},clean_items:{},clean_dates:{},history_delay:0,hits_min:{},delta_min:{},delta_max:{},ga_disabled:false,ga_domain:sDomainTLD,ga_dimensions:{},ym_disabled:false,ym_dimensions:{},callback:[]},"load":function(){try{var mDMP=localStorage.getItem("DMP")||"";if(mDMP){mDMP=fScramble(mDMP);mDMP=JSON.parse(mDMP);if(mDMP&&typeof mDMP==typeof{}){if(oDMP._.debug&&window.console&&console.log)console.log("DMP Retrieved",mDMP);fDMP._=mDMP;
return mDMP}}}catch(_$1){}if(oDMP._.debug&&window.console&&console.log)console.log("DMP Not Retrieved");return null},"store":function(mDMP){if(!mDMP||typeof mDMP!=typeof{})return null;try{localStorage.setItem("DMP",fScramble(JSON.stringify(mDMP)));fDMP._=mDMP;if(oDMP._.debug&&window.console&&console.log)console.log("DMP Stored",mDMP);return true}catch(_$2){}if(oDMP._.debug&&window.console&&console.log)console.log("DMP Not Stored");return false},"track":function(){return fIFrame({"":"DMP","version":oStubDMP.sVersion||
"","domain":oDMP._.domain||"-","debug":oDMP._.debug||false,"read_only":oDMP._.read_only||false,"extended":oDMP._.extended||false,"dmp":fDMP("load")||{},"title":document.title||"","url":location.href||"","referrer":document.referrer||"","user_info":oDMP._.user_info||"","user_data":oDMP._.user_data||{},"context":oDMP._.context||{},"count":oDMP._.count||{},"clean_items":oDMP._.clean_items||{},"clean_dates":oDMP._.clean_dates||{},"history_delay":oDMP._.history_delay||0,"hits_min":oDMP._.hits_min||{},
"delta_min":oDMP._.delta_min||{},"delta_max":oDMP._.delta_max||{},"ga_disabled":oDMP._.ga_disabled||false,"ga_domain":oDMP._.ga_domain||"","ga_dimensions":oDMP._.ga_dimensions||{},"ym_disabled":oDMP._.ym_disabled||false,"ym_dimensions":oDMP._.ym_dimensions||{}})},"domain.set":function(sDomain){if(typeof sDomain!=typeof""||!sDomain)return false;oDMP._.domain=sDomain;return true},"debug.set":function(bDebug){oDMP._.debug=!!bDebug;return true},"read_only.set":function(bReadOnly){oDMP._.read_only=!!bReadOnly;
return true},"extended.set":function(bExtended){oDMP._.extended=!!bExtended;return true},"user:info.set":function(sUserInfo){oDMP._.user_info=""+sUserInfo;return true},"user:data.set":function(oUserData){if(!oUserData||typeof oUserData!=typeof{})return false;oDMP._.user_data=oUserData;return true},"context.set":function(oContext){if(!oContext||typeof oContext!=typeof{})return false;oDMP._.context=oContext;return true},"count.set":function(oCount){if(!oCount||typeof oCount!=typeof{})return false;oDMP._.count=
oCount;return true},"clean:items.set":function(oCleanItems){if(!oCleanItems||typeof oCleanItems!=typeof{})return false;oDMP._.clean_items=oCleanItems;return true},"clean:dates.set":function(oCleanDates){if(!oCleanDates||typeof oCleanDates!=typeof{})return false;oDMP._.clean_dates=oCleanDates;return true},"history:delay.set":function(iDelay){oDMP._.history_delay=parseInt(iDelay,10)||0;return true},"hits:min.set":function(oHitsMin){if(!oHitsMin||typeof oHitsMin!=typeof{})return false;oDMP._.hits_min=
oHitsMin;return true},"delta:min.set":function(oDeltaMin){if(!oDeltaMin||typeof oDeltaMin!=typeof{})return false;oDMP._.delta_min=oDeltaMin;return true},"delta:max.set":function(oDeltaMax){if(!oDeltaMax||typeof oDeltaMax!=typeof{})return false;oDMP._.delta_max=oDeltaMax;return true},"ga:disabled.set":function(bDisabled){oDMP._.ga_disabled=!!bDisabled;return true},"ga:domain.set":function(sDomain){if(!sDomain)return false;oDMP._.ga_domain=""+sDomain;return true},"ga:dimensions.set":function(oDimensions){if(!oDimensions||
typeof oDimensions!=typeof{})return false;oDMP._.ga_dimensions=oDimensions;return true},"ym:disabled.set":function(bDisabled){oDMP._.ym_disabled=!!bDisabled;return true},"ym:dimensions.set":function(oDimensions){if(!oDimensions||typeof oDimensions!=typeof{})return false;oDMP._.ym_dimensions=oDimensions;return true},"callback.add":function(fCallBack){if(!fCallBack||typeof fCallBack!=typeof function(){})return false;oDMP._.callback.push(fCallBack);return true}};var fDMP=function(sFunction){if(!sFunction||
typeof sFunction!=typeof"")return null;if(sFunction=="_")return 0;if(!(sFunction in oDMP)||typeof oDMP[sFunction]!=typeof function(){})return null;return oDMP[sFunction].apply(window,[].slice.call(arguments).slice(1))};fDMP("load");window.DMP=fDMP}{window.addEventListener("message",function(oEvent){{if(!oEvent||!oEvent.data||typeof oEvent.data!=typeof{}||oEvent.data[""]!="DMP")return;delete oEvent.data[""]}if(!oEvent.data.dmp||typeof oEvent.data.dmp!=typeof{}||!oEvent.data.dmp[""]||typeof oEvent.data.dmp[""]!=
typeof{}){if(oDMP._.debug&&window.console&&console.log)console.log("DMP Proxy Received Corrupted Data",oEvent.data);return}if(oDMP._.debug&&window.console&&console.log)console.log("DMP Proxy Received",oEvent.data);fDMP("store",oEvent.data.dmp||{});for(var i=0;i<oDMP._.callback.length;++i)try{if(oDMP._.debug&&window.console&&console.log)console.log("DMP Callback",oDMP._.callback[i]);oDMP._.callback[i]&&oDMP._.callback[i].apply(window,[oEvent.data.dmp,oEvent.data["~dmp"]||null])}catch(_$3){}})}{var fCreateIFrame=
function(bSameDomain){oIFrame=document.createElement("iframe");oIFrame.onload=function(){bIFrame=true;if(oDMP._.debug&&window.console&&console.log)console.log("DMP Proxy Loaded");for(var iIFrame=0;iIFrame<aIFrame.length;++iIFrame)fIFrame.apply(window,aIFrame[iIFrame]);aIFrame=[]};with(oIFrame.style){position="absolute";display="block";width="0";height="0";left="-999999px";top="auto";overflow="hidden";visibility="hidden";margin="0";border="0";padding="0";opacity="0";clip="rect(0,0,0,0)";zIndex="-999999"}oIFrame.src=
(""+location.protocol).toLowerCase()=="file:"?"./index.html":(bSameDomain?"":"https://city-news.it")+"/~shared/do/dmp/?_="+encodeURIComponent(oStubDMP.sVersion||"");if(document.body){document.body.appendChild(oIFrame);return}var aScripts=document.getElementsByTagName("script");if(!aScripts.length)return;var oScript=aScripts[aScripts.length-1];oScript.parentNode.insertBefore(oIFrame,oScript)};fCreateIFrame(!!window.ApplePaySession)}if(oStubDMP.aCommands&&typeof oStubDMP.aCommands==typeof[]&&oStubDMP.aCommands instanceof
Array&&oStubDMP.aCommands.length)for(var iCommand=0;iCommand<oStubDMP.aCommands.length;++iCommand)fDMP.apply(window,oStubDMP.aCommands[iCommand])}();