/* Copyright (C) 1998-2018 DYNAMIC+. All rights reserved. */
(function(){if(!document.createElement||!document.createDocumentFragment)return;if(window.asyncHTML)return;var asyncHTML=function(){var asyncHTML={oInstance:null,aQueue:[],oHook:null,aHook:[],fNext:function(){if(!asyncHTML.aQueue.length){asyncHTML.oInstance=null;return}asyncHTML.oInstance=asyncHTML.aQueue.shift();var oNode=asyncHTML.oInstance.oSiblingNode||asyncHTML.oInstance.oNode||null;var oContext=asyncHTML.oInstance.oSiblingNode||asyncHTML.oInstance.oNode||window;if(asyncHTML.oInstance.fCondition)try{if(asyncHTML.oInstance.fCondition.apply(oContext,
[asyncHTML.oInstance.sHTML])){oNode&&oNode.setAttribute("data-async-html-internal-conditional-skip","");asyncHTML.fNext();return}}catch(_){}{oNode&&oNode.setAttribute("data-async-html-internal-started","");try{asyncHTML.oInstance.fCallStart&&asyncHTML.oInstance.fCallStart.apply(oContext,[asyncHTML.oInstance.sHTML])}catch(_$0){}}if(!asyncHTML.oInstance.oSiblingNode&&!asyncHTML.oInstance.bAppend)asyncHTML.oInstance.oNode.innerHTML="";asyncHTML.fNodeParse(asyncHTML.oInstance.oNode,asyncHTML.oInstance.oSiblingNode,
asyncHTML.oInstance.sHTML,function(){oNode&&oNode.setAttribute("data-async-html-internal-executed","");try{asyncHTML.oInstance.fCallBack&&asyncHTML.oInstance.fCallBack.apply(oContext,[asyncHTML.oInstance.sHTML])}catch(_$1){}asyncHTML.fNext()})},fAdd:function(oInstance){asyncHTML.aQueue.push(oInstance);if(!asyncHTML.oInstance)asyncHTML.fNext()},fWriteHook:function(oParentNode,oSiblingNode){asyncHTML.aHook.push({oParentNode:oParentNode,oSiblingNode:oSiblingNode,sHTML:""});if(!asyncHTML.oHook){var fWrite=
function(sHTML){if(!asyncHTML.aHook.length)return;if(!sHTML)return;asyncHTML.aHook[asyncHTML.aHook.length-1].sHTML+=""+sHTML};asyncHTML.oHook={open:document.open,close:document.close,write:document.write,writeln:document.writeln};document.open=function(){};document.close=function(){};document.write=function(){fWrite(""+[].slice.call(arguments).join(""))};document.writeln=function(){fWrite(""+[].slice.call(arguments).join("")+"\n")}}},fWriteUnHook:function(fCallBack){if(!asyncHTML.aHook.length){fCallBack&&
fCallBack();return}var oHook=asyncHTML.aHook.pop();var fHook=function(){if(!asyncHTML.aHook.length&&asyncHTML.oHook){document.open=asyncHTML.oHook.open;document.close=asyncHTML.oHook.close;document.write=asyncHTML.oHook.write;document.writeln=asyncHTML.oHook.writeln;asyncHTML.oHook=null}fCallBack&&fCallBack();return};if(oHook.sHTML)asyncHTML.fNodeParse(oHook.oParentNode,oHook.oSiblingNode,""+oHook.sHTML,fHook);else fHook()},fNodeIsScript:function(oNode){return oNode.nodeType&&oNode.nodeName&&oNode.nodeType==
1&&(""+oNode.nodeName).toLowerCase()=="script"},fNodeIsStyle:function(oNode){return oNode.nodeType&&oNode.nodeName&&oNode.nodeType==1&&(""+oNode.nodeName).toLowerCase()=="style"},fNodeIsNoScript:function(oNode){return oNode.nodeType&&oNode.nodeName&&oNode.nodeType==1&&(""+oNode.nodeName).toLowerCase()=="noscript"},fNodeCreate:function(oParentNode,oSiblingNode,oNode,fCallBack){asyncHTML.fWriteHook(oParentNode,oSiblingNode);if(asyncHTML.fNodeIsScript(oNode)){var oScript=document.createElement(oNode.nodeName);
if(oNode.hasAttributes())for(var i=0;i<oNode.attributes.length;++i){var oAttribute=oNode.attributes[i];if("specified"in oAttribute&&!oAttribute.specified)continue;oScript.setAttribute(oAttribute.name||"",oAttribute.value||"")}try{oScript.appendChild(document.createTextNode(oNode.text||oNode.textContent||oNode.innerHTML||""))}catch(_){oScript.text=oNode.text||oNode.textContent||oNode.innerHTML||""}if(oScript.getAttribute("src")&&!oScript.hasAttribute("async")&&!oScript.hasAttribute("defer")){var hTimeout=
null;var bScript=false;var fScript=function(){if(bScript)return;bScript=true;if(hTimeout){clearTimeout(hTimeout);hTimeout=null}if(oScript.removeEventListener){oScript.removeEventListener("load",fScript,false);oScript.removeEventListener("error",fScript,false)}else if(oScript.detachEvent){oScript.detachEvent("onload",fScript);oScript.detachEvent("onerror",fScript)}asyncHTML.fWriteUnHook(function(){fCallBack&&fCallBack(oScript)})};if(oScript.addEventListener){oScript.addEventListener("load",fScript,
false);oScript.addEventListener("error",fScript,false)}else if(oScript.attachEvent){oScript.attachEvent("onload",fScript);oScript.attachEvent("onerror",fScript);oScript.attachEvent("onreadystatechange",function(){if(oScript.readyState!="loaded"&&oScript.readyState!="complete")return;oScript.detachEvent("onreadystatechange",arguments.callee);fScript()})}else{var oEvents={onload:oScript.onload||null,onerror:oScript.onerror||null,onreadystatechange:oScript.onreadystatechange||null};oScript.onload=function(){oScript.onload=
oScript.onerror=oScript.onreadystatechange=null;oEvents.onload&&oEvents.onload.apply(oScript,arguments);fScript()};oScript.onerror=function(){oScript.onload=oScript.onerror=oScript.onreadystatechange=null;oEvents.onerror&&oEvents.onerror.apply(oScript,arguments);fScript()};oScript.onreadystatechange=function(){oEvents.onreadystatechange&&oEvents.onreadystatechange.apply(oScript,arguments);if(oScript.readyState!="loaded"&&oScript.readyState!="complete")return;oScript.onload=oScript.onerror=oScript.onreadystatechange=
null;fScript()}}hTimeout=setTimeout(function(){hTimeout=null;fScript()},asyncHTML.oInstance&&asyncHTML.oInstance.iTimeOut?asyncHTML.oInstance.iTimeOut:45E3);try{if(oSiblingNode)oParentNode.insertBefore(oScript,oSiblingNode);else oParentNode.appendChild(oScript)}catch(_$2){fScript()}return}oNode=oScript}else if(asyncHTML.fNodeIsStyle(oNode)){var oStyle=document.createElement(oNode.nodeName);if(oNode.hasAttributes())for(var i=0;i<oNode.attributes.length;++i){var oAttribute=oNode.attributes[i];if("specified"in
oAttribute&&!oAttribute.specified)continue;oStyle.setAttribute(oAttribute.name||"",oAttribute.value||"")}if(oStyle.styleSheet&&!oStyle.sheet)oStyle.styleSheet.cssText=oNode.text||oNode.textContent||oNode.innerHTML||"";else oStyle.appendChild(document.createTextNode(oNode.text||oNode.textContent||oNode.innerHTML||""));oNode=oStyle}else if(asyncHTML.fNodeIsNoScript(oNode)){asyncHTML.fWriteUnHook(function(){fCallBack&&fCallBack(oNode)});return}try{if(oSiblingNode)oParentNode.insertBefore(oNode,oSiblingNode);
else oParentNode.appendChild(oNode)}catch(_$3){}asyncHTML.fWriteUnHook(function(){fCallBack&&fCallBack(oNode)})},fNodeProcess:function(oParentNode,oSiblingNode,oNode,fCallBack){if(asyncHTML.fNodeIsScript(oNode)||asyncHTML.fNodeIsStyle(oNode))asyncHTML.fNodeCreate(oParentNode,oSiblingNode,oNode,fCallBack);else if(asyncHTML.fNodeIsNoScript(oNode))fCallBack&&fCallBack();else{var aNodes=oNode.hasChildNodes()?[].slice.call(oNode.childNodes):[];while(oNode.firstChild)oNode.removeChild(oNode.firstChild);
asyncHTML.fNodeCreate(oParentNode,oSiblingNode,oNode,function(oNewNode){(function(){if(!aNodes.length){fCallBack&&fCallBack();return}asyncHTML.fNodeProcess(oNewNode,null,aNodes.shift(),arguments.callee)})()})}},fNodeParse:function(oParentNode,oSiblingNode,sHTML,fCallBack){if(!sHTML){fCallBack&&fCallBack();return}var oNode=null;if("content"in document.createElement("template")){oNode=document.createElement("template");oNode.innerHTML=""+sHTML;oNode=oNode.content}if(!oNode){oNode=document.createElement("div");
oNode.innerHTML=""+sHTML;var oDocumentFragment=document.createDocumentFragment();{while(oNode.firstChild)oDocumentFragment.appendChild(oNode.firstChild)}oNode=oDocumentFragment}var aNodes=oNode.hasChildNodes()?[].slice.call(oNode.childNodes):[];(function(){if(!aNodes.length){fCallBack&&fCallBack();return}asyncHTML.fNodeProcess(oParentNode,oSiblingNode,aNodes.shift(),arguments.callee)})()},_:function(oArguments){if(!oArguments||typeof oArguments!=typeof{})return;if(!oArguments.oNode)return;{var oNode=
oArguments.oSiblingNode||oArguments.oNode||null;if(oNode){if(oNode.hasAttribute("data-async-html-internal-processed"))return;oNode.setAttribute("data-async-html-internal-processed","")}}this.oNode=oArguments.oNode?oArguments.oNode:null;this.oSiblingNode=oArguments.oSiblingNode?oArguments.oSiblingNode:null;this.iTimeOut=oArguments.iTimeOut?parseInt(oArguments.iTimeOut,10)||0:0;this.bAppend=oArguments.bAppend?true:false;this.sHTML=oArguments.sHTML?""+oArguments.sHTML:"";this.fCondition=oArguments.fCondition&&
typeof oArguments.fCondition==typeof function(){}?oArguments.fCondition:null;this.fCallStart=oArguments.fCallStart&&typeof oArguments.fCallStart==typeof function(){}?oArguments.fCallStart:null;this.fCallBack=oArguments.fCallBack&&typeof oArguments.fCallBack==typeof function(){}?oArguments.fCallBack:null;asyncHTML.fAdd(this)}};return function(oArguments){return new asyncHTML._(oArguments)}}();var aQueueOnDomReady=[];var aQueueOnViewport=[];var fInViewport=function(oNode,bOnlySelector,sSelector,iOffset){oNode=
oNode||null;bOnlySelector=bOnlySelector||false;sSelector=sSelector||"";iOffset=iOffset||0;if(!oNode||!oNode.getBoundingClientRect)return null;var iSizeX=window.innerWidth||(document.documentElement?document.documentElement.clientWidth:0)||(document.body?document.body.clientWidth:0)||0;var iSizeY=window.innerHeight||(document.documentElement?document.documentElement.clientHeight:0)||(document.body?document.body.clientHeight:0)||0;if(!bOnlySelector||!sSelector){var oRect=oNode.getBoundingClientRect();
var bLeftIn=oRect.left+iOffset>=0&&oRect.left-iOffset<=iSizeX;var bRightIn=oRect.right+iOffset>=0&&oRect.right-iOffset<=iSizeX;var bTopIn=oRect.top+iOffset>=0&&oRect.top-iOffset<=iSizeY;var bBottomIn=oRect.bottom+iOffset>=0&&oRect.bottom-iOffset<=iSizeY;var bLeftOut=oRect.left+iOffset<0;var bRightOut=oRect.right-iOffset>iSizeX;var bTopOut=oRect.top+iOffset<0;var bBottomOut=oRect.bottom-iOffset>iSizeY;if((bLeftIn||bRightIn||bLeftOut&&bRightOut)&&(bTopIn||bBottomIn||bTopOut&&bBottomOut))return true}if(sSelector&&
document.querySelectorAll){var aNodes=document.querySelectorAll(sSelector);for(var i=0;i<aNodes.length;++i){var oNode=aNodes[i];if(!oNode.getBoundingClientRect)continue;var oRect=oNode.getBoundingClientRect();var bLeftIn=oRect.left+iOffset>=0&&oRect.left-iOffset<=iSizeX;var bRightIn=oRect.right+iOffset>=0&&oRect.right-iOffset<=iSizeX;var bTopIn=oRect.top+iOffset>=0&&oRect.top-iOffset<=iSizeY;var bBottomIn=oRect.bottom+iOffset>=0&&oRect.bottom-iOffset<=iSizeY;var bLeftOut=oRect.left+iOffset<0;var bRightOut=
oRect.right-iOffset>iSizeX;var bTopOut=oRect.top+iOffset<0;var bBottomOut=oRect.bottom-iOffset>iSizeY;if((bLeftIn||bRightIn||bLeftOut&&bRightOut)&&(bTopIn||bBottomIn||bTopOut&&bBottomOut))return true}}return false};var oOnViewportChangeEvents=null;var hOnViewportChangeTimeout=null;var iOnViewportChangeTimeStamp=null;{var bPassiveSupported=false;try{var oOptions=Object.defineProperty({},"passive",{get:function(){bPassiveSupported=true}});window.addEventListener("test",null,oOptions)}catch(_){}}var bOnViewportChange=
false;var fOnViewportChange=function(){if(!aQueueOnViewport.length)return;if(bOnViewportChange)return;bOnViewportChange=true;{var iTimeStamp=(new Date).getTime();if(iOnViewportChangeTimeStamp>=iTimeStamp-250){if(!hOnViewportChangeTimeout)hOnViewportChangeTimeout=setTimeout(function(){hOnViewportChangeTimeout=null;fOnViewportChange()},250);bOnViewportChange=false;return}iOnViewportChangeTimeStamp=iTimeStamp}do{var bRemovedOnViewport=false;for(var i=0;i<aQueueOnViewport.length;++i){var oCurrentOnViewport=
aQueueOnViewport[i];if(!oCurrentOnViewport.oNodeViewport)continue;if(fInViewport(oCurrentOnViewport.oNodeViewport,oCurrentOnViewport.bOnlySelector,oCurrentOnViewport.sSelector,oCurrentOnViewport.iOffset)){new asyncHTML(oCurrentOnViewport.oArguments);aQueueOnViewport.splice(i,1);bRemovedOnViewport=true;break}}}while(bRemovedOnViewport);if(oOnViewportChangeEvents&&!aQueueOnViewport.length){if(window.removeEventListener){window.removeEventListener("scroll",fOnViewportChange,bPassiveSupported?{passive:true,
capture:false}:false);window.removeEventListener("resize",fOnViewportChange,bPassiveSupported?{passive:true,capture:false}:false)}else if(window.detachEvent){window.detachEvent("onscroll",fOnViewportChange);window.detachEvent("onresize",fOnViewportChange)}else{window.onscroll=oOnViewportChangeEvents.onscroll||null;window.onresize=oOnViewportChangeEvents.onresize||null}oOnViewportChangeEvents=null}bOnViewportChange=false};var fOnViewportChangeHelper=function(){fOnViewportChange();return aQueueOnViewport.length};
var fQueueSetupHelper=function(oNode){if(!oNode.parentNode||!oNode.nodeType||!oNode.nodeName||oNode.nodeType!=1)return null;{if(oNode.hasAttribute("data-async-html-internal-queued"))return false;oNode.setAttribute("data-async-html-internal-queued","")}var sHTML="";var bVirtual=false;switch((""+oNode.nodeName).toLowerCase()){case "script":{sHTML=oNode.text||oNode.textContent||oNode.innerHTML||"";sHTML=sHTML?""+sHTML:"";var oTextArea=document.createElement("textarea");oTextArea.innerHTML=sHTML;sHTML=
oTextArea.value||oTextArea.textContent||oTextArea.innerHTML||"";bVirtual=true;break}case "template":{if(!("content"in oNode))return 0;sHTML=oNode.innerHTML||"";sHTML=sHTML?""+sHTML:"";bVirtual="content"in oNode?true:false;break}default:{if(!oNode.hasAttribute("data-async-html"))return"";sHTML=oNode.getAttribute("data-async-html")||"";sHTML=sHTML?""+sHTML:"";bVirtual=false;break}}var fCondition=oNode.getAttribute("data-async-html-condition")||"";fCondition=fCondition?new Function(""+fCondition):null;
var fCallStart=oNode.getAttribute("data-async-html-callstart")||"";fCallStart=fCallStart?new Function(""+fCallStart):null;var fCallBack=oNode.getAttribute("data-async-html-callback")||"";fCallBack=fCallBack?new Function(""+fCallBack):null;var iPriority=oNode.getAttribute("data-async-html-priority")||0;iPriority=(""+iPriority).replace(/^\s+|\s+$/gm,"")||0;iPriority=parseInt(iPriority,10)||0;var iTimeOut=oNode.getAttribute("data-async-html-timeout")||0;iTimeOut=(""+iTimeOut).replace(/^\s+|\s+$/gm,"")||
0;iTimeOut=parseInt(iTimeOut,10)||0;var bAppend=oNode.hasAttribute("data-async-html-append")?true:false;if(oNode.hasAttribute("data-async-html-on-viewport")){var sSelector=oNode.getAttribute("data-async-html-viewport-selector")||"";sSelector=sSelector?""+sSelector:"";var bOnlySelector=oNode.hasAttribute("data-async-html-viewport-only-selector")?true:false;var iOffset=oNode.getAttribute("data-async-html-viewport-offset")||250;iOffset=(""+iOffset).replace(/^\s+|\s+$/gm,"")||0;iOffset=parseInt(iOffset,
10)||0;iOffset=iOffset>=0?iOffset:0;if(bVirtual){oNode.style.position="relative";oNode.style.display="block";oNode.style.width="0px";oNode.style.height="0px";oNode.style.overflow="hidden";oNode.style.visibility="hidden";oNode.style.margin="0px";oNode.style.border="0px";oNode.style.padding="0px"}if(fInViewport(oNode,bOnlySelector,sSelector,iOffset))aQueueOnDomReady.push({oArguments:{oNode:bVirtual?oNode.parentNode:oNode,oSiblingNode:bVirtual?oNode:null,sHTML:sHTML,fCondition:fCondition,fCallStart:fCallStart,
fCallBack:fCallBack,iTimeOut:iTimeOut,bAppend:bAppend},iPriority:iPriority});else aQueueOnViewport.push({oArguments:{oNode:bVirtual?oNode.parentNode:oNode,oSiblingNode:bVirtual?oNode:null,sHTML:sHTML,fCondition:fCondition,fCallStart:fCallStart,fCallBack:fCallBack,iTimeOut:iTimeOut,bAppend:bAppend},iPriority:iPriority,oNodeViewport:oNode,bOnlySelector:bOnlySelector,sSelector:sSelector,iOffset:iOffset})}else aQueueOnDomReady.push({oArguments:{oNode:bVirtual?oNode.parentNode:oNode,oSiblingNode:bVirtual?
oNode:null,sHTML:sHTML,fCondition:fCondition,fCallStart:fCallStart,fCallBack:fCallBack,iTimeOut:iTimeOut,bAppend:bAppend},iPriority:iPriority});return true};var fQueueSetup=function(mSelector){var aQueueSetup=[];if(mSelector)if(typeof mSelector==typeof{}){if(fQueueSetupHelper(mSelector))aQueueSetup.push(mSelector)}else{if(document.querySelectorAll){var aNodes=document.querySelectorAll(""+mSelector);for(var i=0;i<aNodes.length;++i){var oNode=aNodes[i];if(!fQueueSetupHelper(oNode))continue;aQueueSetup.push(oNode)}}}else{if(document.getElementsByTagName){var aNodes=
document.getElementsByTagName("script");for(var i=0;i<aNodes.length;++i){var oNode=aNodes[i];if(!oNode.getAttribute("type")||!/^\s*text\/+async[\._-]*html\s*$/i.test(""+oNode.getAttribute("type")))if(!oNode.hasAttribute("data-async-html"))continue;if(!fQueueSetupHelper(oNode))continue;aQueueSetup.push(oNode)}}if(document.querySelectorAll){var aNodes=document.querySelectorAll("[data-async-html]");for(var i=0;i<aNodes.length;++i){var oNode=aNodes[i];if(!oNode.hasAttribute("data-async-html"))continue;
if(!fQueueSetupHelper(oNode))continue;aQueueSetup.push(oNode)}}}aQueueOnDomReady.sort(function(oAsyncHTMLA,oAsyncHTMLB){return oAsyncHTMLA.iPriority-oAsyncHTMLB.iPriority});aQueueOnViewport.sort(function(oAsyncHTMLA,oAsyncHTMLB){return oAsyncHTMLA.iPriority-oAsyncHTMLB.iPriority});var oCurrentOnDomReady;while(oCurrentOnDomReady=aQueueOnDomReady.shift())new asyncHTML(oCurrentOnDomReady.oArguments);if(!oOnViewportChangeEvents&&aQueueOnViewport.length){oOnViewportChangeEvents={onscroll:null,onresize:null};
if(window.addEventListener){window.addEventListener("scroll",fOnViewportChange,bPassiveSupported?{passive:true,capture:false}:false);window.addEventListener("resize",fOnViewportChange,bPassiveSupported?{passive:true,capture:false}:false)}else if(window.attachEvent){window.attachEvent("onscroll",fOnViewportChange);window.attachEvent("onresize",fOnViewportChange)}else{var fOnScroll=window.onscroll||null;window.onscroll=function(){fOnScroll&&fOnScroll.apply(window,arguments);fOnViewportChange()};var fOnResize=
window.onresize||null;window.onresize=function(){fOnResize&&fOnResize.apply(window,arguments);fOnViewportChange()};oOnViewportChangeEvents={onscroll:fOnScroll,onresize:fOnResize}}}if(aQueueOnViewport.length)fOnViewportChange();return aQueueSetup};var bPageReady=false;var fPageReady=function(){if(bPageReady)return false;bPageReady=true;fQueueSetup(null);return true};if(document.readyState=="complete"||document.readyState=="loaded"||!document.attachEvent&&document.readyState=="interactive")setTimeout(function(){fPageReady()},
1);else{var bOnDomReady=false;var fOnDomReady=function(){if(bOnDomReady)return;bOnDomReady=true;if(document.removeEventListener)document.removeEventListener("DOMContentLoaded",fOnDomReady,false);if(window.removeEventListener)window.removeEventListener("load",fOnDomReady,false);else if(window.detachEvent)window.detachEvent("onload",fOnDomReady);fPageReady()};if(document.addEventListener)document.addEventListener("DOMContentLoaded",fOnDomReady,false);else if(document.attachEvent){document.attachEvent("onreadystatechange",
function(){if(document.readyState!="complete"&&document.readyState!="loaded")return;document.detachEvent("onreadystatechange",arguments.callee);fOnDomReady()});if(document.documentElement&&document.documentElement.doScroll&&window==window.top)(function(){if(bOnDomReady)return;try{document.documentElement.doScroll("left")}catch(_$4){setTimeout(arguments.callee,100);return}fOnDomReady()})()}if(window.addEventListener)window.addEventListener("load",fOnDomReady,false);else if(window.attachEvent)window.attachEvent("onload",
fOnDomReady);else{var fOnLoad=window.onload||null;window.onload=function(){window.onload=null;fOnLoad&&fOnLoad.apply(window,arguments);fOnDomReady()}}(function(){if(bPageReady)return;if(document.readyState=="complete"||document.readyState=="loaded"||!document.attachEvent&&document.readyState=="interactive"){setTimeout(function(){fPageReady()},1);return}setTimeout(arguments.callee,100)})()}if(window.$&&$.fn)$.fn.asyncHTML=function(){return this.each(function(){fQueueSetup(this)})};asyncHTML.setup=
fQueueSetup;asyncHTML.ready=fPageReady;asyncHTML.view=fOnViewportChangeHelper;window.asyncHTML=asyncHTML})();